server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-dev
    username: minishop
    password: minishop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
